version: '3.7'

services:
  dev:
    build: ./
    ports:
      - '1234:1234'
    volumes:
      - '~/Documents/development:/home/docker/development'
      - '~/Documents/ssh-config:/home/docker/.ssh'
      - 'dev-box:/home/docker'

volumes:
  dev-box:
